services:
  goaccess:
    build: .
    image: kyxap/goaccess
    restart: unless-stopped
    container_name: goaccess_server
    ports:
      - "127.0.0.1:7890:7890"
    volumes:
      - data:/srv/data
      - logs:/srv/logs
      - report:/srv/report
      - /var/log/nginx/access.log:/srv/logs/access.log:ro
      - ./goaccess.conf:/srv/data/goaccess.conf:ro

volumes:
  data: {}
  logs: {}
  report: {}