version: '3'

services:
  mqtt-proxy:
    image: nginx
    ports:
      - 1883:1883
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - mqtt-server

  mqtt-server:
    image: eclipse-mosquitto
    ports:
      - 1884:1883
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf