services:
  mqtt:
    image: eclipse-mosquitto
    expose:
      - 1883
      - 9001
    environment:
      HTTP_PORT: 1883
      VIRTUAL_HOST: euskelec.arraiz.me
      LETSENCRYPT_HOST: euskelec.arraiz.me
      LETSENCRYPT_EMAIL: "mikeldiezgarcia@gmail.com"
    networks:
      webservices-network:


networks:
  webservices-network:
    external: true
  