services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: temp_page
    environment:
      HTTP_PORT: 80
      VIRTUAL_HOST: arraiz.me
      #LETSENCRYPT_HOST: www.arraiz.me
      #LETSENCRYPT_EMAIL: "mikeldiezgarcia@gmail.com"
    volumes:
    - html:/var/www/html
    networks:
      webservices-network:

networks:
  webservices-network:
    external: true