services:
  nginx-proxy-no-ssl:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    container_name: nginx-proxy-no-ssl
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      webservices-network:

networks:
  webservices-network:
    name: webservices-network